name: Publish to PyPI

on:
  release:
    types: [published]    # fires when Release Please publishes the release

permissions:
  id-token: write         # required for PyPI Trusted Publishing
  contents: read

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Check out
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install build tooling
        run: |
          python -m pip install --upgrade pip
          python -m pip install build twine

      - name: Build sdist and wheel
        run: python -m build

      - name: Twine check
        run: twine check dist/*

      - name: Publish to PyPI (Trusted Publishing)
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          # When using Trusted Publishing, no username/password needed.
          # It will use the OIDC token provided by GitHub automatically.
          print-hash: true